export const ROUND_STRINGS = {
  da: {
    "meta.title": "Runde-tracker – GKR Heavy Hitters",
    "meta.description": "Fasetracker og to-hit til GKR: Heavy Hitters.",
    hubBack: "← GKRTools",
    tagline: "Hold runden kørende – uden at bladre i regelbogen.",
    footer: "Fan tool · Ikke tilknyttet Weta Workshop / Cryptozoic",
    "round.label": "Runde {n}",
    "action.prev": "← Forrige",
    "action.next": "Næste fase →",
    "action.reset": "↺ Ny kamp",
    "rules.link": "Regelreference →",
    "hit.title": "To-hit",
    "hit.hh": "Heavy Hitter (5+)",
    "hit.su": "Support (7+)",
    "hit.cover": "Delvis dækning +1",
    "hit.alley": "Alley shot +2",
    "hit.flank": "Flank −1",
    "hit.full": "Fuld dækning",
    "hit.result": "Rul {n}+",
    "hit.blocked": "Ingen direkte ild – missil + spotter, eller orbital",
    "hit.crit": "Dobbelt 6 = crit (ingen armor). Dobbelt 1 = fail.",
    "phase.deploy.name": "Deploy",
    "phase.deploy.hint":
      "Glory Hound først, derefter med uret. 1 support pr. spiller, tom hex inden for 2 hexes af jeres HH. Deploy-kort = 2 energi. Uden kort = 4 energi.",
    "phase.move-hh.name": "Bevæg HH",
    "phase.move-hh.hint":
      "Glory Hound først. 1 energi pr. hex. Kan gå gennem egne units, ikke ende på optaget hex. Kan ende på fjendtlig support (modstander flytter den). Ikke gennem fjendtlig HH eller bygning. Drej gratis. Kritisk energi: 1 skade pr. ekstra punkt.",
    "phase.move-combat.name": "Bevæg Combat",
    "phase.move-combat.hint":
      "Glory Hound først. Bevægelse står på kortet – koster ikke energi. Ikke gennem fjender eller bygninger. Spring over hvis enheden ikke er ude.",
    "phase.move-repair.name": "Bevæg Repair",
    "phase.move-repair.hint":
      "Glory Hound først. Bevægelse står på kortet. Ikke gennem fjender eller bygninger. Spring over hvis enheden ikke er ude.",
    "phase.move-recon.name": "Bevæg Recon",
    "phase.move-recon.hint":
      "Glory Hound først. Recon kan flyve gennem optagede hexes og bygninger, men ikke ende der. Flyvning giver ikke LOS over bygninger. Mercs bevæger sig efter Recon.",
    "phase.combat.name": "Kamp",
    "phase.combat.hint":
      "1. Læg våben facedown + support faceup. Kun 1 af hvert unikt våben. 2. Vend samtidig, betal energi. 3. Resolv højeste speed først. Orbital: ethvert mål, ingen LOS. Support der dør før den skyder, skyder ikke. Ubrugte våben tilbage i hånden (energi tilbagebetales ikke).",
    "phase.tag.name": "Tagging",
    "phase.tag.hint":
      "Glory Hound først. Alle units kan tagge 1 tilstødende bygningsside (facing ligegyldigt). Over-tag er lovligt. 1 sponsor pr. forskellig bygning. Max 5 sponsorer. 4. tag på en bygning = demolér med det samme (sejr ved 4 demolitions).",
    "phase.reset.name": "Reset",
    "phase.reset.hint":
      "Reaktor til +5. Træk/smid til 6 faction-kort (damage-bunken kommer ikke tilbage). Flest tags = ny Glory Hound. Ved lighed: nærmeste med uret – nuværende GH beholder den ikke. Stjæl GH = +1 achievement.",
    "pill.deploy": "Deploy",
    "pill.move-hh": "HH",
    "pill.move-combat": "Combat",
    "pill.move-repair": "Repair",
    "pill.move-recon": "Recon",
    "pill.combat": "Kamp",
    "pill.tag": "Tag",
    "pill.reset": "Reset",
  },
  en: {
    "meta.title": "Round tracker – GKR Heavy Hitters",
    "meta.description": "Phase tracker and to-hit helper for GKR: Heavy Hitters.",
    hubBack: "← GKRTools",
    tagline: "Keep the round moving – without flipping the rulebook.",
    footer: "Fan tool · Not affiliated with Weta Workshop / Cryptozoic",
    "round.label": "Round {n}",
    "action.prev": "← Previous",
    "action.next": "Next phase →",
    "action.reset": "↺ New match",
    "rules.link": "Rules reference →",
    "hit.title": "To-hit",
    "hit.hh": "Heavy Hitter (5+)",
    "hit.su": "Support (7+)",
    "hit.cover": "Partial cover +1",
    "hit.alley": "Alley shot +2",
    "hit.flank": "Flank −1",
    "hit.full": "Full cover",
    "hit.result": "Roll {n}+",
    "hit.blocked": "No direct fire – missile + spotter, or orbital",
    "hit.crit": "Double 6 = crit (no armor). Double 1 = fail.",
    "phase.deploy.name": "Deploy",
    "phase.deploy.hint":
      "Glory Hound first, then clockwise. 1 support per player, empty hex within 2 hexes of your HH. Deploy card = 2 energy. No card = 4 energy.",
    "phase.move-hh.name": "Move HH",
    "phase.move-hh.hint":
      "Glory Hound first. 1 energy per hex. May pass through your own units, cannot end on an occupied hex. May end on an enemy support (opponent displaces it). Not through an enemy HH or a building. Rotate for free. Critical energy: 1 damage per extra point.",
    "phase.move-combat.name": "Move Combat",
    "phase.move-combat.hint":
      "Glory Hound first. Move value is on the card – no energy cost. Not through enemies or buildings. Skip if the unit is not deployed.",
    "phase.move-repair.name": "Move Repair",
    "phase.move-repair.hint":
      "Glory Hound first. Move value is on the card. Not through enemies or buildings. Skip if the unit is not deployed.",
    "phase.move-recon.name": "Move Recon",
    "phase.move-recon.hint":
      "Glory Hound first. Recon may fly through occupied hexes and buildings, but cannot end there. Flying does not grant LOS over buildings. Mercs move after Recon.",
    "phase.combat.name": "Combat",
    "phase.combat.hint":
      "1. Place weapons facedown + supports faceup. Only 1 of each unique weapon. 2. Flip together, pay energy. 3. Resolve highest speed first. Orbital: any target, no LOS. A support destroyed before it fires does not shoot. Unused weapons return to hand (energy is not refunded).",
    "phase.tag.name": "Tagging",
    "phase.tag.hint":
      "Glory Hound first. Every unit may tag 1 adjacent building face (facing does not matter). Over-tagging is legal. 1 sponsor per different building. Max 5 sponsors. 4th tag on a building = demolish immediately (win at 4 demolitions).",
    "phase.reset.name": "Reset",
    "phase.reset.hint":
      "Reactor back to +5. Draw/discard to 6 faction cards (the damage pile never returns). Most tags = new Glory Hound. On a tie: closest clockwise – the current GH does not keep it. Steal GH = +1 achievement.",
    "pill.deploy": "Deploy",
    "pill.move-hh": "HH",
    "pill.move-combat": "Combat",
    "pill.move-repair": "Repair",
    "pill.move-recon": "Recon",
    "pill.combat": "Combat",
    "pill.tag": "Tag",
    "pill.reset": "Reset",
  },
};
